language: php
os: linux
dist: bionic
sudo: false
services:
  - memcached

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  # set up PHP config
  - phpenv config-add tests/php.ini

install:
  # install Composer packages, will also trigger dump-autoload
  - composer require -n --ignore-platform-reqs "phwoolcon/ci-pecl-cacher" "phpunit/phpunit:^7" "friendsofphp/php-cs-fixer" "php-coveralls/php-coveralls"
  - composer install -n --ignore-platform-reqs --no-suggest

  # install and cache PHP extensions
  - ./vendor/bin/ci-pecl-install memcached

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - ./test.sh

matrix:
  fast_finish: true
